spring.application.name=backend
spring.datasource.url=jdbc:postgresql://ep-lucky-cloud-ataj49yx-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_li6Yseahpm1d&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_li6Yseahpm1d